services:
  - type: web
    name: news-digest-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GNEWS_API_KEY
        sync: false
